Use CPM package manager

diff --git a/ct-build b/ct-build
--- a/ct-build
+++ b/ct-build
@@ -24,20 +24,26 @@ curr_dir=$(pwd)
 build_with_cmake() {
   local build_dir=$(get_build_dir "${build_type}")
   set -x
-  cmake  -B ${build_dir} \
-         -DCMAKE_BUILD_TYPE=${build_type} \
-         -G "${GENERATOR}" \
-         -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-         -DCMAKE_CXX_COMPILER=clang++ \
-         -DCMAKE_CXX_FLAGS=-stdlib=libc++ \
-         "${curr_dir}"
+  cmake -B ${build_dir} \
+    -DCMAKE_BUILD_TYPE=${build_type} \
+    -G "${GENERATOR}" \
+    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
+    -DCMAKE_CXX_COMPILER=clang++ \
+    -DCMAKE_CXX_FLAGS=-stdlib=libc++ \
+    "${curr_dir}"
   set +x
   return $?
 }
 
 reset=$(tput sgr0)
-  red=$(tput sgr0; tput setaf 1)
-green=$(tput sgr0; tput setaf 2)
+red=$(
+  tput sgr0
+  tput setaf 1
+)
+green=$(
+  tput sgr0
+  tput setaf 2
+)
 
 build_type='debug'
 generator='make'
@@ -68,12 +74,12 @@ show_help() {
 clean_build_dir() {
   what=$1
   if [[ "${what}" == "" ]]; then
-    rm -rf cmake-build-*
+    yes | rm -rf cmake-build-*
     echo "${green}All project builds cleared${reset}"
   else
     build_dir=$(get_build_dir "${what}")
     rm -rf "${build_dir}"
-   echo "${green}Project build '${what}' cleared${reset}"
+    echo "${green}Project build '${what}' cleared${reset}"
   fi
 }
 
@@ -83,12 +89,12 @@ get_build_dir() {
 
 set_generator() {
   case ${generator} in
-  "make" )
+  "make")
     BUILDER=$(command -v make)
     GENERATOR="CodeBlocks - Unix Makefiles"
     VERBOSE_FLAG='VERBOSE=1'
     ;;
-  "ninja" )
+  "ninja")
     BUILDER=$(command -v ninja)
     GENERATOR="CodeBlocks - Ninja"
     VERBOSE_FLAG='-v'
@@ -100,52 +106,51 @@ set_generator() {
   esac
 }
 
-
 options=$(getopt -o chdg:vb:j: --long clean::,help,debug,verbose,generator:,build:,jobs: -- "$@")
 [ $? -eq 0 ] || {
-    echo "${red}Incorrect options provided.${reset}"
-    exit 1
+  echo "${red}Incorrect options provided.${reset}"
+  exit 1
 }
 eval set -- "$options"
 while [[ $# -gt 0 ]]; do
   case "$1" in
-  -h | --help )
+  -h | --help)
     show_help
     shift
     exit 0
     ;;
-  -d | --debug )
+  -d | --debug)
     show_options=true
     shift
     ;;
-  -v | --verbose )
+  -v | --verbose)
     verbose=true
     shift
     ;;
-  -g | --generator )
+  -g | --generator)
     generator="$2"
     shift 2
     ;;
-  -b | --build )
+  -b | --build)
     build_type="$2"
     shift 2
     ;;
-  -j | --jobs )
+  -j | --jobs)
     jobs="$2"
     shift 2
     ;;
-  -c )
+  -c)
     clean_build_dir ""
     shift
     ;;
-  --clean )
+  --clean)
     clean_build_dir "$2"
     shift 2
     ;;
-  -- )
-      shift
-      break
-      ;;
+  --)
+    shift
+    break
+    ;;
   *)
     echo "Internal error!"
     exit 1
@@ -160,8 +165,8 @@ if [ "$show_options" = true ]; then
   print_options
 fi
 
-if [[ "${verbose}" == "false" ]] ; then
-    VERBOSE_FLAG=""
+if [[ "${verbose}" == "false" ]]; then
+  VERBOSE_FLAG=""
 fi
 
 #
@@ -169,13 +174,13 @@ fi
 #
 if [ ! -d "${build_dir}" ]; then
   mkdir -p "${build_dir}"
-#  pushd "${build_dir}" > /dev/null || exit
+  #  pushd "${build_dir}" > /dev/null || exit
 
-  if build_with_cmake;  then
-      echo "${green}Configure OK${reset}"
+  if build_with_cmake; then
+    echo "${green}Configure OK${reset}"
   else
-      echo "${red}Configure FAILED${reset}"
-      exit 1
+    echo "${red}Configure FAILED${reset}"
+    exit 1
   fi
 #  popd || exit
 fi
@@ -184,11 +189,11 @@ fi
 # Step 2: Build
 #
 cd "${build_dir}" || exit
-if ${BUILDER} -j "${jobs}"  ${VERBOSE_FLAG} ; then
-    echo "${green}Build OK${reset}"
+if ${BUILDER} -j "${jobs}" ${VERBOSE_FLAG}; then
+  echo "${green}Build OK${reset}"
 else
-    echo "${red}Build FAILED${reset}"
-    exit 1
+  echo "${red}Build FAILED${reset}"
+  exit 1
 fi
 
 #
@@ -196,7 +201,7 @@ fi
 #
 cd "$curr_dir" || exit
 if [[ ! "$1" == "" ]]; then
-  cmd=$1;
+  cmd=$1
   shift
   eval "$cmd" "$*"
 fi
